#是针对开发环境的特定配置文件，包含仅适用于开发环境的配置。

sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jiangqianli12138

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tR8k8GDvB6dJ2mnPUF5
    access-key-secret: bi3pxJQpqOR4bfPFbCQc4S4SriZfga
    bucket-name: cangqiongwaimei
